name: Latest blog post workflow

on:
  schedule: # Run workflow automatically
    # - cron: '0 0 * * *' # Runs every day at 00:00
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog-posts:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOG_FEED_UPDATE"
          commit_message: "Updated readme with latest blog posts"
          feed_list: "https://www.codequoi.com/en/feed/"
